// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8ZXH5XpU6ZRlJQ7VuYXyza0YLWbqjrY',
    appId: '1:852480928285:web:97d2e15f23319d6dc034f4',
    messagingSenderId: '852480928285',
    projectId: 'batteryalarm-845a4',
    authDomain: 'batteryalarm-845a4.firebaseapp.com',
    storageBucket: 'batteryalarm-845a4.appspot.com',
    measurementId: 'G-V8M4QDNH77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtQrQ8DFcJvMzhTunr0o7X5TWimYOwS3I',
    appId: '1:852480928285:android:3f5230522dd81faec034f4',
    messagingSenderId: '852480928285',
    projectId: 'batteryalarm-845a4',
    storageBucket: 'batteryalarm-845a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtN2ExUeSGZ4SsORmf5qRtsjY7Bfah0Qw',
    appId: '1:852480928285:ios:3f60e3acf3facd78c034f4',
    messagingSenderId: '852480928285',
    projectId: 'batteryalarm-845a4',
    storageBucket: 'batteryalarm-845a4.appspot.com',
    iosBundleId: 'com.batterychargealarm.batteryalert.chargealarm.batteryInfo.batteryalarm.batterycharge',
  );
}
